### ISSUE TITLE
Level generator

### ISSUE THREAD

**Issue by daniellimws** [jeffsieu/last-man-sitting#102]
Builds on the stuff in #101.

Every pixel in this map texture represents 8x8 units in the room map texture, i.e. 1/4 of a room. This is so that the corridor can be only half the width of a room, which makes more sense.

![image](https://user-images.githubusercontent.com/8130120/80918142-f186ac80-8d95-11ea-95f1-59a309e46f10.png)

In the example above, the red pixel indicates where the player starts. The light blue pixels represent the corridor. The 2x2 blocks of pixels represent different rooms, with the top left pixel indicating the type of room and the other 3 pixels are just filler pixels.

The parsing makes use of JSON just like #101. The level information will be stored in a `Level` class with a `List<Tuple<Vector2, string> >` that stores each objects position and their corresponding scene path.

Since the corridor is most likely going to be connected throughout, we might be able to make a CSG mesh that contains the whole corridor at once to reduce the amount of resources in the game.

**Comment by jeffsieu** [comment]
I think it will be better to combine the level and room map? Cos if we do it like this, this means that every room of the same type will be of the same size. And we can't tell the exact room size from this floor-level image.

**Comment by daniellimws** [comment]
I think we should fix the size of a room. Like mentioned in #101, it is 16x16. I think it is reasonable that every room will have the same size.

Also I thought you agreed we should separate the room map and level map.

**Comment by jeffsieu** [comment]
Hmm, but I'm not sure if fixing each room as 16x16 will be good though, cos for now we haven't rly tested whether that size will be optimal? I guess we can always tweak the fixed size, but I think fixed size means less variety in terms of room design.

And I also agree that the room and floor generation should be separated, but I thought that it would be better to have one overall map for the whole floor's generation.

I guess this way will make the level iteration and redesign process faster, but also means less flexibility and variety in level design.

What do you think?

**Comment by daniellimws** [comment]
Suppose we have a level like this. We can trace the outline of a room and pass it to a room generator. But how can we easily pass the information inside the room to the room generator? Passing the coordinates of the bounds? But for non-rectangular shapes how to do this?

![image](https://user-images.githubusercontent.com/8130120/80931093-4c49f380-8dea-11ea-9596-a9d3c85b6126.png)

That's why I think we should separate the room details from the level map. Level map to determine the layout, while room map for details inside a room. Abstraction nam sayin.

By 16x16 it doesn't necessarily mean that the room has to be a 16x16 square box, just saying the image has to be 16x16 for parsing purposes. It can look something like this.

![image](https://user-images.githubusercontent.com/8130120/80931026-fecd8680-8de9-11ea-8e80-3fa8ee0b0c7f.png)

**Comment by jeffsieu** [comment]
@daniellimws Can possibly pass the individual pixels, then get the room generator to trace instead? Meaning in the first-level parsing of the file, we can just loop through the image row by row. Then when we detect a wall of a certain color, we know its part of the outline from that same-colored room. Since multiple rooms may have the same color, we can assign map every pixel to a room id, where adjacent same-colored pixels get assigned to the same id.

Using this way, every time we hit a wall, we just need to see the four adjacent pixels to determine which room this wall is part of.

In this picture, assume we're doing a pass on the outlined row. When we hit the blue pixels on the outlined row, we can see which room it is in by looking at the pixel on top of it.
![image](https://user-images.githubusercontent.com/8487294/80931360-e8282f00-8deb-11ea-87e6-954c6a68fed4.png)


 Then now we can return a `List<Vector2[]> rooms`, each room being an ordered array of pixels representing the outline of the room's floor space as a polygon. Shouldn't this be enough to make a `Polygon2D` (for map creation) or `CSGPolygon` (for mesh creation)?

**Comment by daniellimws** [comment]
Think we settled this alr
